[target.'cfg(not(target_arch = "wasm32"))'] # lld is not supported for wasm
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[alias]
rsontest = "hack test -q --feature-powerset --skip default -F arbitrary -F serde --ignore-unknown-features"

[env]
RUST_BACKTRACE = "1"
