[book]
title = "rsonbook"
authors = ["Mateusz Gienieczko <mat@gienieczko.com>"]
description = "User and developer guide for the rsonpath project."
src = "src"
language = "en"

[rust]
edition = "2021"

[build]
build-dir = "wwwroot"

[preprocessor.katex]
after = ["links"]

[output.html]
preferred-dark-theme = "ayu"
smart_punctuation = true
mathjax-support = false # we use katex
additional-css = ["rsonbook.css"]
git-repository-url = "https://github.com/rsonquery/rsonpath"
edit-url-template = "https://github.com/rsonquery/rsonpath/edit/main/book/{path}"
