name: New Issue
on:
  issues:
    types: [opened, reopened]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      repository-projects: write

    steps:
    - uses: V0ldek/modify-label@v1.0.0
      id: add-label
      with:
        action: add
        issue-number: ${{ github.event.issue.number }}
        label-id: 'LA_kwDOHodxeM8AAAABA8dlvA'
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Issue comment tag
      uses: devops-actions/issue-comment-tag@v0.1.4
      with:
        # The tag of the team to mention in the issue comment
        team: V0ldek
        # The issue number to create a new comment in
        issue: ${{ github.event.issue.number }}
        # The owner for the repo to create a new comment in
        owner: ${{ github.event.repository.owner.login }}
        # The repo to create a new comment in
        repo: ${{ github.event.repository.name }}
        # The GitHub token to use to create a new comment with. Use `secrets.GITHUB_TOKEN` to inject it
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Add To GitHub projects
      uses: actions/add-to-project@v0.4.0
      with:
        # URL of the project to add issues to
        project-url: https://github.com/users/V0ldek/projects/1
        # A GitHub personal access token with write access to the project
        github-token: ${{ secrets.RSONPATH_PROJECT_TOKEN }}
